# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users # Autogenerated by devise
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'addresses#index'
  resources :addresses

  namespace "api", constraints: { format: 'json' } do
    get "/addresses/search/:address", :to=>"addresses#search"
  end

end
